<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritoSeeder extends Seeder
{
    static $distritos = [
        ['CHACHAPOYAS',1],
        ['BAGUA',2],
        ['BAGUA GRANDE',3],
        ['SAN NICOLAS',4],
        ['FLORIDA',5],
        ['LA JALCA',1],
        ['CAMPORREDONDO',6],
        ['CAJARURO',3],
        ['YAMBRASBAMBA',5],
        ['VALERA',5],
        ['LONYA GRANDE',3],
        ['LA PECA',2],
        ['MARIA',6],
        ['LUYA',6],
        ['JAZAN',5],
        ['TINGO',6],
        ['JAMALCA',3],
        ['OCALLI',6],
        ['SAN FRANCISCO DE DAGUAS',1],
        ['LEIMEBAMBA',1],
        ['NIEVA',7],
        ['ARAMANGO',2],
        ['IMAZA',2],
        ['SAN JERONIMO',6],
        ['COROSHA',5],
        ['SANTO TOMAS',6],
        ['MOLINOPAMPA',1],
        ['LEVANTO',1],
        ['CHIRIMOTO',4],
        ['MILPUC',4],
        ['CASMA',8],
        ['NUEVO CHIMBOTE',9],
        ['CATAC',10],
        ['CARAZ',11],
        ['COISHCO',9],
        ['CHIMBOTE',9],
        ['YAUTAN',8],
        ['HUARAZ',12],
        ['INDEPENDENCIA',12],
        ['SAN MARCOS',13],
        ['CABANA',14],
        ['CULEBRAS',15],
        ['CONCHUCOS',14],
        ['ELEAZAR GUZMAN BARRON',16],
        ['ALFONSO UGARTE',17],
        ['FIDEL OLIVAS ESCUDERO',16],
        ['SANTA CRUZ',11],
        ['YAUYA',18],
        ['ACZO',19],
        ['HUAYLLACAYAN',20],
        ['COCHAPETI',15],
        ['CAJAY',13],
        ['MANCOS',21],
        ['CARHUAZ',22],
        ['HUARMEY',15],
        ['PAMPAS',14],
        ['YURACMARCA',11],
        ['LLAMELLIN',19],
        ['MORO',9],
        ['SIHUAS',17],
        ['SAMANCO',9],
        ['ANTONIO RAYMONDI',20],
        ['NEPEÑA',9],
        ['COMANDANTE NOEL',8],
        ['TINCO',22],
        ['RECUAY',10],
        ['CHAVIN DE HUANTAR',13],
        ['PIRA',12],
        ['ACOPAMPA',22],
        ['SANTA',9],
        ['POMABAMBA',23],
        ['SAN PEDRO DE CHANA',13],
        ['HUACHIS',13],
        ['AQUIA',20],
        ['YUNGAY',21],
        ['MARCARA',22],
        ['SHUPLUY',21],
        ['JANGAS',12],
        ['CHIQUIAN',20],
        ['PISCOBAMBA',16],
        ['SAN LUIS',18],
        ['HUAYLAS',11],
        ['PUEBLO LIBRE',11],
        ['HUALLANCA',20],
        ['BOLOGNESI',14],
        ['AIJA',24],
        ['LACABAMBA',14],
        ['CHINGAS',19],
        ['CHACAS',25],
        ['TARICA',12],
        ['HUACCHIS',13],
        ['OCROS',26],
        ['COLQUIOC',20],
        ['LLAPO',14],
        ['CACERES DEL PERU',9],
        ['PAMPAROMAS',11],
        ['BUENA VISTA ALTA',8],
        ['QUILLO',21],
        ['CORIS',24],
        ['CORONGO',27],
        ['COLCABAMBA',12],
        ['SAN PEDRO',26],
        ['COCHAS',26],
        ['HUANDOVAL',14],
        ['HUARI',13],
        ['RANRAHIRCA',21],
        ['SAN JUAN DE RONTOY',19],
        ['BAMBAS',27],
        ['YUPAN',27],
        ['ANRA',13],
        ['HUAYAN',15],
        ['LLAMA',16],
        ['LLIPA',26],
        ['ACOBAMBA',17],
        ['HUANTAR',13],
        ['OLLEROS',12],
        ['COCHABAMBA',12],
        ['CUTERVO',29],
        ['CAJAMARCA',30],
        ['SAN IGNACIO',31],
        ['JAEN',32],
        ['CHOTA',33],
        ['LOS BAÑOS DEL INCA',30],
        ['CELENDIN',34],
        ['BELLAVISTA',32],
        ['PEDRO GALVEZ',35],
        ['CONTUMAZA',36],
        ['PUCARA',32],
        ['SAN BERNARDINO',37],
        ['CHILETE',36],
        ['HUARANGO',31],
        ['BAMBAMARCA',38],
        ['LAJAS',33],
        ['SOCOTA',29],
        ['CHIRINOS',31],
        ['UTICYACU',39],
        ['CHOROS',29],
        ['ENCAÑADA',30],
        ['SAN PABLO',37],
        ['CATACHE',39],
        ['CONDEBAMBA',40],
        ['SAN FELIPE',32],
        ['HUASMIN',34],
        ['COLASAY',32],
        ['LA COIPA',31],
        ['TACABAMBA',33],
        ['CHUGUR',38],
        ['ASUNCION',30],
        ['YONAN',36],
        ['CHUMUCH',34],
        ['CHANCAYBAÑOS',39],
        ['HUALGAYOC',38],
        ['CACHACHI',40],
        ['SALLIQUE',32],
        ['MAGDALENA',30],
        ['OXAMARCA',34],
        ['TANTARICA',36],
        ['LLAMA',33],
        ['JOSE SABOGAL',35],
        ['ICHOCAN',35],
        ['CHETILLA',30],
        ['CAJABAMBA',40],
        ['SAN MIGUEL',41],
        ['SAN JUAN',30],
        ['MATARA',30],
        ['CHONTALI',32],
        ['TABACONAS',31],
        ['SANTA ROSA',32],
        ['JOSE GALVEZ',34],
        ['NAMORA',30],
        ['POMAHUACA',32],
        ['SEXI',39],
        ['LLACANORA',30],
        ['CALLAYUC',29],
        ['SAN LUIS DE LUCMA',29],
        ['SANTA CRUZ',39],
        ['JESUS',30],
        ['TORIBIO CASANOVA',29],
        ['COCHABAMBA',33],
        ['NIEPOS',41],
        ['CHALAMARCA',33],
        ['QUEROCOTO',33],
        ['CONCHAN',33],
        ['CUJILLO',29],
        ['UTCO',34],
        ['MIGUEL IGLESIAS',34],
        ['CUPISNIQUE',36],
        ['GUZMANGO',36],
        ['SAN BENITO',36],
        ['ANGUIA',33],
        ['CHANCAY',35],
        ['JOSE MANUEL QUIROZ',35],
        ['UNION AGUA BLANCA',41],
        ['SAN GREGORIO',41],
        ['MIRACOSTA',33],
        ['SAN JUAN DE LICUPIS',33],
        ['TOCMOCHE',33],
        ['NANCHOC',41],
        ['SAN JOSE DE LOURDES',31],
        ['SANTO TOMAS',29],
        ['SOROCHUCO',34],
        ['PULAN',39],
        ['HUAMBOS',33],
        ['LA LIBERTAD DE PALLAN',34],
        ['ANDABAMBA',39],
        ['NAMBALLE',31],
        ['TUMBADEN',37],
        ['SITACOCHA',40],
        ['BOLIVAR',41],
        ['CHAO',42],
        ['VICTOR LARCO HERRERA',43],
        ['TRUJILLO',43],
        ['EL PORVENIR',43],
        ['HUANCHACO',43],
        ['HUAMACHUCO',44],
        ['TAYABAMBA',45],
        ['VIRU',42],
        ['CHEPEN',46],
        ['MOCHE',43],
        ['LA ESPERANZA',43],
        ['SAN PEDRO DE LLOC',47],
        ['RAZURI',48],
        ['LAREDO',43],
        ['SAYAPULLO',49],
        ['PATAZ',45],
        ['FLORENCIA DE MORA',43],
        ['PACANGA',46],
        ['HUANCASPATA',45],
        ['CASCAS',49],
        ['PACASMAYO',47],
        ['PUEBLO NUEVO',46],
        ['MACHE',50],
        ['USQUIL',50],
        ['SANTIAGO DE CHUCO',51],
        ['JEQUETEPEQUE',47],
        ['SALAVERRY',43],
        ['COCHORCO',44],
        ['SANTA CRUZ DE CHUCA',51],
        ['CHILLIA',45],
        ['PARCOY',45],
        ['ANGASMARCA',51],
        ['GUADALUPITO',42],
        ['SANTIAGO DE CAO',48],
        ['SARTIMBAMBA',44],
        ['OTUZCO',50],
        ['CASA GRANDE',48],
        ['CHICAMA',48],
        ['CHUGAY',44],
        ['HUASO',52],
        ['LUCMA',49],
        ['BAMBAMARCA',53],
        ['SANAGORAN',44],
        ['LONGOTEA',53],
        ['SARIN',44],
        ['CALAMARCA',52],
        ['CARABAMBA',52],
        ['SAN JOSE',47],
        ['GUADALUPE',47],
        ['MOLLEBAMBA',51],
        ['PAIJAN',48],
        ['CACHICADAN',51],
        ['CURGOS',44],
        ['ASCOPE',48],
        ['QUIRUVILCA',51],
        ['HUAYO',45],
        ['SALPO',50],
        ['JULCAN',52],
        ['CHOCOPE',48],
        ['SINSICAP',50],
        ['SIMBAL',43],
        ['UCHUMARCA',53],
        ['BOLIVAR',53],
        ['ONGON',45],
        ['SITABAMBA',51],
        ['POROTO',43],
        ['OLMOS',54],
        ['MONSEFU',55],
        ['LAMBAYEQUE',54],
        ['CHICLAYO',55],
        ['PIMENTEL',55],
        ['PUCALA',55],
        ['LA VICTORIA',55],
        ['FERREÑAFE',56],
        ['PUEBLO NUEVO',56],
        ['JOSE LEONARDO ORTIZ',55],
        ['JAYANCA',54],
        ['MOTUPE',54],
        ['PATAPO',55],
        ['TUCUME',54],
        ['PICSI',55],
        ['MANUEL ANTONIO MESONES MURO',56],
        ['NUEVA ARICA',55],
        ['SAN JOSE',54],
        ['REQUE',55],
        ['SANTA ROSA',55],
        ['TUMAN',55],
        ['PITIPO',56],
        ['OYOTUN',55],
        ['CHONGOYAPE',55],
        ['MORROPE',54],
        ['PACORA',54],
        ['ILLIMO',54],
        ['SAÑA',55],
        ['CAÑARIS',56],
        ['MOCHUMI',54],
        ['CAYALTI',55],
        ['SALAS',54],
        ['INCAHUASI',56],
        ['LAGUNAS',55],
        ['POMALCA',55],
        ['ETEN',55],
        ['VEINTISEIS DE OCTUBRE',57],
        ['HUARMACA',58],
        ['PIURA',57],
        ['SULLANA',59],
        ['CASTILLA',57],
        ['PARIÑAS',60],
        ['MORROPON',61],
        ['AYABACA',62],
        ['CATACAOS',57],
        ['EL ALTO',60],
        ['PAITA',63],
        ['CHULUCANAS',61],
        ['TAMBO GRANDE',57],
        ['LA HUACA',63],
        ['SECHURA',64],
        ['LOS ORGANOS',60],
        ['LA ARENA',57],
        ['BELLAVISTA',59],
        ['RINCONADA LLICUAR',64],
        ['LAS LOMAS',57],
        ['PAIMAS',62],
        ['JILILI',62],
        ['SANTO DOMINGO',61],
        ['MANCORA',60],
        ['CURA MORI',57],
        ['HUANCABAMBA',58],
        ['CRISTO NOS VALGA',64],
        ['LA MATANZA',61],
        ['MIGUEL CHECA',59],
        ['BERNAL',64],
        ['VICHAYAL',63],
        ['QUERECOTILLO',59],
        ['CHALACO',61],
        ['TAMARINDO',63],
        ['FRIAS',62],
        ['MARCAVELICA',59],
        ['SUYO',62],
        ['LAGUNAS',62],
        ['PACAIPAMPA',62],
        ['SALITRAL',59],
        ['LA UNION',57],
        ['VICE',64],
        ['LA BREA',60],
        ['COLAN',63],
        ['BUENOS AIRES',61],
        ['YAMANGO',61],
        ['SONDORILLO',58],
        ['SAPILLICA',62],
        ['LOBITOS',60],
        ['SAN MIGUEL DE EL FAIQUE',58],
        ['MONTERO',62],
        ['SAN JUAN DE BIGOTE',61],
        ['AMOTAPE',63],
        ['IGNACIO ESCUDERO',59],
        ['ZORRITOS',66],
        ['TUMBES',67],
        ['CORRALES',67],
        ['LA CRUZ',67],
        ['ZARUMILLA',68],
        ['CANOAS DE PUNTA SAL',66],
        ['CASITAS',66],
        ['AGUAS VERDES',68],
        ['MATAPALO',68],
        ['SAN JACINTO',67],
        ['PAPAYAL',68],
        ['PAMPAS DE HOSPITAL',67],
        ['SAN JUAN DE LA VIRGEN',67],
        ['N/D', 69]
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::getSchemaBuilder()->disableForeignKeyConstraints();
        DB::table('distritos')->truncate();
        DB::getSchemaBuilder()->enableForeignKeyConstraints();
        //DB::statement('SET FOREIGN_KEY_CHECKS = 0;'); // Desactivamos la revisión de claves foráneas
        // DB::statement('ALTER TABLE distritos NOCHECK CONSTRAINT ALL;');
        // DB::table('distritos')->truncate();
        // DB::statement('ALTER TABLE distritos CHECK CONSTRAINT ALL;');
        //DB::statement('SET FOREIGN_KEY_CHECKS = 1;');

        foreach (self::$distritos as $distrito) {
            DB::table('distritos')->insert([
                'nombre' => $distrito[0],
                'provincia_id' => $distrito[1]
            ]);
        }
    }
}
