<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritoSeeder extends Seeder
{
    static $distritos = [
        ['FLORENCIA DE MORA', 1],
        ['LA ESPERANZA', 1],
        ['COISHCO', 2],
        ['ACZO', 3],
        ['TUMBES', 4],
        ['PATAZ', 5],
        ['CAJAMARCA', 6],
        ['BELLAVISTA', 7],
        ['JESUS', 6],
        ['CAYALTI', 8],
        ['PUCALA', 8],
        ['LUCMA', 9],
        ['CHACHAPOYAS', 10],
        ['AGUAS VERDES', 11],
        ['PIURA', 12],
        ['AIJA', 13],
        ['NUEVO CHIMBOTE', 2],
        ['CHUGAY', 14],
        ['CASTILLA', 12],
        ['QUIRUVILCA', 15],
        ['PARIÑAS', 16],
        ['EL PORVENIR', 1],
        ['CHICLAYO', 8],
        ['SULLANA', 17],
        ['TRUJILLO', 1],
        ['AMOTAPE', 18],
        ['LA VICTORIA', 8],
        ['HUARAZ', 19],
        ['JOSE LEONARDO ORTIZ', 8],
        ['HUALGAYOC', 20],
        ['ANGASMARCA', 15],
        ['ANRA', 21],
        ['SAN MARCOS', 21],
        ['ARAMANGO', 22],
        ['LAGUNAS', 23],
        ['CAMPORREDONDO', 24],
        ['ASCOPE', 25],
        ['ALFONSO UGARTE', 26],
        ['SAYAPULLO', 9],
        ['HUANCHACO', 1],
        ['AYABACA', 23],
        ['BAGUA', 22],
        ['BAGUA GRANDE', 27],
        ['BAMBAMARCA', 20],
        ['BAMBAS', 28],
        ['LOS BAÑOS DEL INCA', 6],
        ['SECHURA', 29],
        ['VICE', 29],
        ['BERNAL', 29],
        ['SAN IGNACIO', 30],
        ['SAN JUAN DE BIGOTE', 31],
        ['CAJABAMBA', 32],
        ['CHONGOYAPE', 8],
        ['BOLIVAR', 33],
        ['NIEPOS', 33],
        ['CHUMUCH', 35],
        ['BUENOS AIRES', 31],
        ['BOLOGNESI', 36],
        ['ZORRITOS', 37],
        ['CACERES DEL PERU', 2],
        ['CACHACHI', 32],
        ['CACHICADAN', 15],
        ['COPALLIN', 22],
        ['CAJARURO', 27],
        ['CULEBRAS', 38],
        ['LA CRUZ', 4],
        ['SAN JOSE', 39],
        ['MONSEFU', 8],
        ['OLMOS', 39],
        ['VIRU', 40],
        ['INDEPENDENCIA', 19],
        ['CANOAS DE PUNTA SAL', 37],
        ['CAÑARIS', 41],
        ['HUALLANCA', 42],
        ['LAREDO', 1],
        ['CARABAMBA', 43],
        ['CARAZ', 42],
        ['CARHUAZ', 44],
        ['CASA GRANDE', 25],
        ['ENCAÑADA', 6],
        ['LA HUACA', 18],
        ['PIMENTEL', 8],
        ['SANTIAGO DE CAO', 25],
        ['LA ARENA', 12],
        ['MAGDALENA', 6],
        ['CASCAS', 9],
        ['COLAN', 18],
        ['CASITAS', 37],
        ['CASMA', 45],
        ['CATACAOS', 12],
        ['TANTARICA', 46],
        ['CONDEBAMBA', 32],
        ['CELENDIN', 35],
        ['SUCRE', 35],
        ['CHOTA', 47],
        ['HUARMEY', 38],
        ['MORROPON', 31],
        ['SALPO', 48],
        ['RAZURI', 25],
        ['CHACAS', 49],
        ['SAN LUIS', 50],
        ['CHALAMARCA', 47],
        ['SAN PEDRO DE CHANA', 21],
        ['FIDEL OIIVAS ESCUDERO', 51],
        ['CHANCAY', 52],
        ['CHAO', 40],
        ['COLQUIOC', 53],
        ['CHAVIN DE HUANTAR', 21],
        ['CHEPEN', 54],
        ['CHETILLA', 6],
        ['CHICAMA', 25],
        ['CHILETE', 46],
        ['PAMPAS CHICO', 36],
        ['CHIQUIAN', 53],
        ['IMAZA', 22],
        ['MILPUC', 55],
        ['CHIRINOS', 30],
        ['QUERECOTILLO', 17],
        ['CHOCOPE', 25],
        ['CHONTALI', 7],
        ['CHULUCANAS', 31],
        ['MIGUEL IGLESIAS', 35],
        ['GUADALUPE', 56],
        ['VICTOR LARCO HERRERA', 1],
        ['COCHABAMBA', 47],
        ['COLCABAMBA', 19],
        ['LACABAMBA', 36],
        ['CONTUMAZA', 46],
        ['SAN PEDRO', 58],
        ['LA PECA', 22],
        ['ANTONIO RAIMONDI', 53],
        ['CORIS', 13],
        ['CORONGO', 28],
        ['HUAMACHUCO', 14],
        ['GUADALUPITO', 40],
        ['TAMBOGRANDE', 12],
        ['MORROPE', 39],
        ['CUJILLO', 59],
        ['TORIBIO CASANOVA', 59],
        ['CURA MORI', 12],
        ['CURGOS', 14],
        ['CUTERVO', 59],
        ['USQUIL', 48],
        ['SAN FRANCISCO DE DAGUAS', 10],
        ['CATAC', 57],
        ['RECUAY', 57],
        ['LLAMA', 47],
        ['EL ALTO', 16],
        ['FLORIDA', 60],
        ['SARIN', 14],
        ['JOSE SABOGAL', 52],
        ['PAPAYAL', 11],
        ['SIHUAS', 26],
        ['UNION AGUA BLANCA', 33],
        ['LA COIPA', 30],
        ['SANTIAGO DE CHUCO', 15],
        ['MOCHE', 1],
        ['PAITA', 18],
        ['ETEN', 8],
        ['SAN MIGUEL DE EL FAIQUE', 61],
        ['LAMBAYEQUE', 39],
        ['PUEBLO NUEVO', 41],
        ['FRIAS', 23],
        ['PACANGA', 54],
        ['YONAN', 46],
        ['MOLLEBAMBA', 15],
        ['GUZMANGO', 46],
        ['JAEN', 7],
        ['ELEAZAR GUZMAN BARRON', 51],
        ['HUACCHIS', 21],
        ['HUACHIS', 21],
        ['HUACRACHUCO', 62],
        ['SAMANCO', 2],
        ['HUAMBOS', 47],
        ['HUANCABAMBA', 61],
        ['HUANCASPATA', 5],
        ['COCHAS', 58],
        ['HUANDOVAL', 36],
        ['ACOBAMBA', 26],
        ['HUANTAR', 21],
        ['HUARANGO', 30],
        ['CAJAY', 21],
        ['SANTA CRUZ', 42],
        ['HUASO', 43],
        ['HUARMACA', 61],
        ['PACAIPAMPA', 23],
        ['HUAYAN', 38],
        ['HUAYLAS', 42],
        ['TUCUME', 39],
        ['INCAHUASI', 41],
        ['JAMALCA', 27],
        ['JAYANCA', 39],
        ['JEQUETEPEQUE', 56],
        ['JULCAN', 43],
        ['COROSHA', 60],
        ['SALAS', 39],
        ['TINGO', 24],
        ['SAN MIGUEL', 33],
        ['LA BREA', 16],
        ['NAMORA', 6],
        ['SEXI', 63],
        ['OXAMARCA', 35],
        ['LA LIBERTAD DE PALLAN', 35],
        ['LA MATANZA', 31],
        ['LAS LOMAS', 12],
        ['LA UNION', 12],
        ['SARTIMBAMBA', 14],
        ['PULAN', 63],
        ['SAN JUAN', 6],
        ['LAJAS', 47],
        ['SAN FELIPE', 7],
        ['LEIMEBAMBA', 10],
        ['LEVANTO', 10],
        ['SAN JOSE DE LOURDES', 30],
        ['SAN JUAN DE LICUPIS', 47],
        ['HUANCAS', 10],
        ['LLACANORA', 6],
        ['PARCOY', 5],
        ['PIRA', 19],
        ['LLAMELLIN', 3],
        ['LLAPO', 36],
        ['LLIPA', 58],
        ['SITACOCHA', 32],
        ['LONGOTEA', 34],
        ['LONYA GRANDE', 27],
        ['CALAMARCA', 43],
        ['SANAGORAN', 14],
        ['LOS ORGANOS', 16],
        ['LUYA', 24],
        ['MARCAVELICA', 17],
        ['MANCORA', 16],
        ['MANCOS', 64],
        ['MANSERICHE', 65],
        ['YAUYA', 50],
        ['MARCARA', 44],
        ['CHIRIMOTO', 55],
        ['MATAPALO', 11],
        ['MATARA', 6],
        ['MIRACOSTA', 47],
        ['MOCHUMI', 39],
        ['MOLINOPAMPA', 10],
        ['PACORA', 39],
        ['MONTERO', 23],
        ['MORO', 2],
        ['MOTUPE', 39],
        ['PITIPO', 41],
        ['CHIMBOTE', 2],
        ['NAMBALLE', 30],
        ['NANCHOC', 33],
        ['FERREÑAFE', 41],
        ['PACASMAYO', 56],
        ['IGNACIO ESCUDERO', 17],
        ['ANDABAMBA', 63],
        ['SALLIQUE', 7],
        ['OCALLI', 24],
        ['OCROS', 58],
        ['POMAHUACA', 7],
        ['OLLEROS', 19],
        ['ONGON', 5],
        ['OTUZCO', 48],
        ['HUAYO', 5],
        ['OYOTUN', 8],
        ['PAIJAN', 25],
        ['PAIMAS', 23],
        ['PAMPAROMAS', 42],
        ['PAMPAS DE HOSPITAL', 4],
        ['ICHOCAN', 52],
        ['PATAPO', 8],
        ['TUMBADEN', 66],
        ['JAZAN', 60],
        ['PICSI', 8],
        ['JANGAS', 19],
        ['CALLAYUC', 59],
        ['PISCOBAMBA', 51],
        ['LOBITOS', 16],
        ['SAN JACINTO', 4],
        ['POMABAMBA', 67],
        ['POMALCA', 8],
        ['POROTO', 1],
        ['PUCARA', 7],
        ['QUEROCOTO', 47],
        ['SOCOTA', 59],
        ['QUILLO', 64],
        ['CONCHUCOS', 36],
        ['SAPILLICA', 23],
        ['COCHORCO', 14],
        ['MARIA', 24],
        ['REQUE', 8],
        ['SALAVERRY', 1],
        ['SAN NICOLAS', 55],
        ['SALITRAL', 17],
        ['SAN BENITO', 46],
        ['SAN BUENAVENTURA', 62],
        ['SAN GREGORIO', 33],
        ['SINSICAP', 48],
        ['CORRALES', 4],
        ['NEPEÑA', 2],
        ['SAN JERONIMO', 24],
        ['SAN JUAN DE LA VIRGEN', 4],
        ['SAN JUAN DE RONTOY', 3],
        ['ANGUIA', 47],
        ['SANTA', 2],
        ['PEDRO GALVEZ', 52],
        ['VALERA', 60],
        ['SAN PABLO', 66],
        ['CHOLON', 62],
        ['CONCHAN', 47],
        ['SAN PEDRO DE LLOC', 56],
        ['SUYO', 23],
        ['COCHAPETI', 38],
        ['NIEVA', 68],
        ['SANTA ROSA', 8],
        ['CHALACO', 31],
        ['SANTO TOMAS', 59],
        ['TINCO', 44],
        ['JOSE MANUEL QUIROZ', 52],
        ['SHUPLUY', 64],
        ['TAYABAMBA', 5],
        ['SIMBAL', 1],
        ['SAÑA', 8],
        ['SITABAMBA', 15],
        ['SONDORILLO', 61],
        ['SOROCHUCO', 35],
        ['JOSE GALVEZ', 35],
        ['TABACONAS', 30],
        ['TACABAMBA', 47],
        ['TARICA', 19],
        ['ILLIMO', 39],
        ['TOCMOCHE', 47],
        ['COMANDANTE NOEL', 45],
        ['CUPISNIQUE', 46],
        ['TUMAN', 8],
        ['UCHUMARCA', 34],
        ['CHINGAS', 3],
        ['CATACHE', 63],
        ['UTCO', 35],
        ['YAMANGO', 31],
        ['YAMBRASBAMBA', 60],
        ['YAUTAN', 45],
        ['SAN LUIS DE LUCMA', 59],
        ['HUAYLLACAYAN', 53],
        ['YUNGAY', 64],
        ['YUPAN', 28],
        ['YURACMARCA', 42],
        ['ZARUMILLA', 11],
        ['HUASMIN', 35],
        ['CHARAT', 48],
        ['ASUNCION', 6],
        ['SANTA CRUZ DE CHUCA', 15],
        ['CHUGUR', 20],
        ['HUARI', 21],
        ['RANRAHIRCA', 64],
        ['AQUIA', 53],
        ['VEINTISEIS DE OCTUBRE', 12],
        ['LA JALCA', 10],
        ['PARIAHUANCA', 44],
        ['NUEVA ARICA', 8],
        ['COLASAY', 7],
        ['TAMARINDO', 18],
        ['VICHAYAL', 18],
        ['CRISTO NOS VALGA', 29],
        ['MANUEL ANTONIO MESONES MURO', 41],
        ['ACOPAMPA', 44],
        ['UTICYACU', 63],
        ['PUEBLO LIBRE', 42],
        ['MACHE', 48],
        ['SAN JOSE DEL ALTO', 7],
        ['SANTO DOMINGO', 31],
        ['RINCONADA-LLICUAR', 29],
        ['JILILI', 23],
        ['EL MILAGRO', 27],
        ['CHOROS', 59],
        ['MIGUEL CHECA', 17],
        ['HUASTA', 53],
        ['BUENA VISTA ALTA',45],
        ['CHILLIA',	5],
        ['MAGDALENA DE CAO',25],
        ['LONGUITA',24],
        ['MOLLEPATA',15],
        ['N/D', 69]
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::getSchemaBuilder()->disableForeignKeyConstraints();
        DB::table('distritos')->truncate();
        DB::getSchemaBuilder()->enableForeignKeyConstraints();
        //DB::statement('SET FOREIGN_KEY_CHECKS = 0;'); // Desactivamos la revisión de claves foráneas
        // DB::statement('ALTER TABLE distritos NOCHECK CONSTRAINT ALL;');
        // DB::table('distritos')->truncate();
        // DB::statement('ALTER TABLE distritos CHECK CONSTRAINT ALL;');
        //DB::statement('SET FOREIGN_KEY_CHECKS = 1;');

        foreach (self::$distritos as $distrito) {
            DB::table('distritos')->insert([
                'nombre' => $distrito[0],
                'provincia_id' => $distrito[1]
            ]);
        }
    }
}
