<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalidadeSeeder extends Seeder
{
    static $municipalidades = [
        '26 DE OCTUBRE',
        'ACOBAMBA',
        'ACZO',
        'AGUAS VERDES',
        'AIJA',
        'ALFONSO UGARTE',
        'AMOTAPE',
        'ANDABAMBA',
        'ANGASMARCA',
        'ANGUIA',
        'ANRA',
        'ANTONIO RAYMONDI',
        'ARAMANGO',
        'ASCOPE',
        'AYABACA',
        'BAGUA',
        'BAGUA GRANDE',
        'BAMBAMARCA',
        'BAMBAS',
        'BAÑOS DEL INCA',
        'BELLAVISTA',
        'BELLAVISTA SULLANA',
        'BERNAL',
        'BOLIVAR',
        'BOLOGNESI',
        'BUENA VISTA ALTA',
        'BUENOS AIRES',
        'CACERES DEL PERU',
        'CACHACHI',
        'CACHICADAN',
        'CAJABAMBA',
        'CAJAMARCA',
        'CAJARURO',
        'CAJAY',
        'CALAMARCA',
        'CALLAYUC',
        'CAMPORREDONDO',
        'CANOAS DE PUNTA SAL',
        'CAÑARIS',
        'CARABAMBA',
        'CARAZ',
        'CARHUAZ',
        'CASA GRANDE',
        'CASCAS',
        'CASITAS',
        'CASMA',
        'CASTILLA',
        'CATACAOS',
        'CATACHE',
        'CAYALTI',
        'CELENDIN',
        'CHACAS',
        'CHACHAPOYAS',
        'CHALACO',
        'CHALAMARCA',
        'CHAMAYA',
        'CHANCAY',
        'CHAO',
        'CHAVIN DE HUANTAR',
        'CHEPEN',
        'CHETILLA',
        'CHICAMA',
        'CHICLAYO',
        'CHILETE',
        'CHILLIA',
        'CHIMBOTE',
        'CHINGAS',
        'CHIQUIAN',
        'CHIQUITOY',
        'CHIRIMOTO',
        'CHIRINOS',
        'CHOCOPE',
        'CHONGOYAPE',
        'CHONTALI',
        'CHOTA',
        'CHUGAY',
        'CHULUCANAS',
        'CHUMUCH',
        'COCHABAMBA',
        'COCHAPETI',
        'COCHAS',
        'COISHCO',
        'COLAN',
        'COLCABAMBA',
        'COLQUIOC',
        'COMANDANTE NOEL',
        'CONCHAN',
        'CONCHUCOS',
        'CONDEBAMBA',
        'CONTUMAZA',
        'CORIS',
        'CORONGO',
        'COROSHA',
        'CORRALES',
        'CUJILLO',
        'CULEBRAS',
        'CUPISNIQUE',
        'CURA MORI',
        'CURGOS',
        'CUTERVO',
        'EL ALTO',
        'EL PORVENIR',
        'ELEAZAR GUZMAN BARRON',
        'ENCAÑADA',
        'ETEN',
        'FERREÑAFE',
        'FIDEL OLIVAS ESCUDERO',
        'FLORENCIA DE MORA',
        'FLORIDA',
        'FRIAS',
        'GUADALUPE',
        'GUADALUPITO',
        'GUZMANGO',
        'HUACCHIS',
        'HUACHIS',
        'HUALGAYOC',
        'HUALLANCA',
        'HUAMACHUCO',
        'HUAMBOS',
        'HUANCABAMBA',
        'HUANCASPATA',
        'HUANCHACO',
        'HUANDOVAL',
        'HUANTAR',
        'HUARANGO',
        'HUARAZ',
        'HUARMACA',
        'HUARMEY',
        'HUASO',
        'HUAYAN',
        'HUAYLAS',
        'HUAYLLACAYAN',
        'HUAYO',
        'ICHOCAN',
        'IGNACIO ESCUDERO',
        'ILLIMO',
        'IMAZA',
        'INCAHUASI',
        'INDEPENDENCIA',
        'JAEN',
        'JAMALCA',
        'JANGAS',
        'JAYANCA',
        'JAZAN',
        'JEQUETEPEQUE',
        'JESUS',
        'JOSE GALVEZ',
        'JOSE LEONARDO ORTIZ',
        'JOSE MANUEL QUIROZ',
        'JOSE SABOGAL',
        'JULCAN',
        'LA ARENA',
        'LA BREA',
        'LA COIPA',
        'LA CRUZ',
        'LA ESPERANZA',
        'LA HUACA',
        'LA LIBERTAD DE PALLAN',
        'LA MATANZA',
        'LA PECA',
        'LA UNION',
        'LA VICTORIA',
        'LACABAMBA',
        'LAGUNAS',
        'LAJAS',
        'LAMBAYEQUE',
        'LAMUD',
        'LAREDO',
        'LAS LOMAS',
        'LEIMEBAMBA',
        'LEVANTO',
        'LLACANORA',
        'LLAMA',
        'LLAMELLIN',
        'LLAPO',
        'LLIPA',
        'LOBITOS',
        'LONGOTEA',
        'LONYA GRANDE',
        'LOS BAÑOS DEL INCA',
        'LOS ORGANOS',
        'LUCMA',
        'LUYA',
        'MAGDALENA',
        'MANCORA',
        'MANCOS',
        'Mansiche, Trujillo',
        'MARCARA',
        'MARCAVELICA',
        'MARIA',
        'MATAPALO',
        'MATARA',
        'MIGUEL IGLESIAS',
        'MILPUC',
        'MIRACOSTA',
        'MOCHE',
        'MOCHUMI',
        'MOLINOPAMPA',
        'MONSEFU',
        'MONTERO',
        'MORO',
        'MORROPE',
        'MORROPON',
        'MOTUPE',
        'Municipalidad Morropon',
        'NAMBALLE',
        'NAMORA',
        'NANCHOC',
        'NEPEÑA',
        'NIEPOS',
        'NIEVA',
        'NUEVO CHIMBOTE',
        'OCALLI',
        'OCROS',
        'OLMOS',
        'ONGON',
        'OTUZCO',
        'OXAMARCA',
        'OYOTUN',
        'PACAIPAMPA',
        'PACANGA',
        'PACASMAYO',
        'PACORA',
        'PAIJAN',
        'PAIMAS',
        'PAITA',
        'PAMPAROMAS',
        'PAMPAS CHICO',
        'PAMPAS DE HOSPITAL',
        'PAMPAS PALLASCA',
        'PAPAYAL',
        'PARCOY',
        'PARIÑAS',
        'PATAPO',
        'PATAZ',
        'PEDRO GALVEZ',
        'PICSI',
        'PIMENTEL',
        'PIRA',
        'PISCOBAMBA',
        'PITIPO',
        'PIURA',
        'POMABAMBA',
        'POMAHUACA',
        'POMALCA',
        'POROTO',
        'PUCALA',
        'PUCARA',
        'PUEBLO NUEVO',
        'PULAN',
        'QUERECOTILLO',
        'QUEROCOTO',
        'QUILLO',
        'QUIRUVILCA',
        'RAZURI',
        'RECUAY',
        'REQUE',
        'SALAS',
        'SALAVERRY',
        'SALITRAL',
        'SALLIQUE',
        'SALPO',
        'SAMANCO',
        'SAN BENITO',
        'SAN FELIPE',
        'SAN FRANCISCO DE DAGUAS',
        'SAN GREGORIO',
        'SAN IGNACIO',
        'SAN JACINTO',
        'SAN JERONIMO',
        'SAN JOSE',
        'SAN JOSE DE LOURDES',
        'SAN JUAN',
        'SAN JUAN DE BIGOTE',
        'SAN JUAN DE LA VIRGEN',
        'SAN JUAN DE LICUPIS',
        'SAN JUAN DE RONTOY',
        'SAN LUIS',
        'SAN LUIS DE LUCMA',
        'SAN MARCOS',
        'SAN MIGUEL',
        'SAN MIGUEL DE EL FAIQUE',
        'SAN NICOLAS',
        'SAN PABLO',
        'SAN PEDRO',
        'SAN PEDRO DE CHANA',
        'SAN PEDRO DE LLOC',
        'SANAGORAN',
        'SANCHEZ CARRION',
        'SANTA',
        'SANTA CRUZ',
        'SANTA ROSA',
        'SANTIAGO DE CAO',
        'SANTIAGO DE CHUCO',
        'SANTO TOMAS',
        'SAÑA',
        'SAPILLICA',
        'SARIN',
        'SARTIMBAMBA',
        'SAYAPULLO',
        'SECHURA',
        'SEXI',
        'SHUPLUY',
        'SIHUAS',
        'SIMBAL',
        'SINSICAP',
        'SITABAMBA',
        'SITACOCHA',
        'SOCOTA',
        'SONDORILLO',
        'SOROCHUCO',
        'SUCRE',
        'SULLANA',
        'SUYO',
        'TABACONAS',
        'TACABAMBA',
        'TAMBO GRANDE',
        'TANTARICA',
        'TARICA',
        'TAYABAMBA',
        'TINCO',
        'TINGO',
        'TOCMOCHE',
        'TORIBIO CASANOVA',
        'TRUJILLO',
        'TUCUME',
        'TUMAN',
        'TUMBADEN',
        'TUMBES',
        'UCHUMARCA',
        'UNION',
        'UNION AGUA BLANCA',
        'USQUIL',
        'UTCO',
        'VICE',
        'VICTOR LARCO HERRERA',
        'VIRU',
        'YAMANGO',
        'YAMBRASBAMBA',
        'YAUTAN',
        'YAUYA',
        'YONAN',
        'YUNGAY',
        'YUPAN',
        'YURACMARCA',
        'ZARUMILLA',
        'ZORRITOS',
        'N/D'


    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::$municipalidades as $municipalidade) {
            DB::table('municipalidades')->insert([
                'nombre' => $municipalidade
            ]);
        }
    }
}
